export const FETCH_ITEM_GROUPS_REQUEST = 'FETCH_ITEM_GROUPS_REQUEST';
export const FETCH_ITEM_GROUPS_FAILED = 'FETCH_ITEM_GROUPS_FAILED';
export const FETCH_ITEM_GROUPS_SUCCESS = 'FETCH_ITEM_GROUPS_SUCCESS';
export const SET_ITEM_GROUPS_PAGER = 'SET_ITEM_GROUPS_PAGER';

export const FETCH_ITEM_GROUP_REQUEST = 'FETCH_ITEM_GROUP_REQUEST';
export const FETCH_ITEM_GROUP_FAILED = 'FETCH_ITEM_GROUP_FAILED';
export const FETCH_ITEM_GROUP_SUCCESS = 'FETCH_ITEM_GROUP_SUCCESS';

export const ADD_ITEM_GROUPS_REQUEST = 'ADD_ITEM_GROUPS_REQUEST';
export const ADD_ITEM_GROUPS_FAILED = 'ADD_ITEM_GROUPS_FAILED';
export const ADD_ITEM_GROUPS_SUCCESS = 'ADD_ITEM_GROUPS_SUCCESS';

export const UPDATE_ITEM_GROUPS_REQUEST = 'UPDATE_ITEM_GROUPS_REQUEST';
export const UPDATE_ITEM_GROUPS_FAILED = 'UPDATE_ITEM_GROUPS_FAILED';
export const UPDATE_ITEM_GROUPS_SUCCESS = 'UPDATE_ITEM_GROUPS_SUCCESS';

export const DELETE_ITEM_GROUPS_REQUEST = 'DELETE_ITEM_GROUPS_REQUEST';
export const DELETE_ITEM_GROUPS_FAILED = 'DELETE_ITEM_GROUPS_FAILED';
export const DELETE_ITEM_GROUPS_SUCCESS = 'DELETE_ITEM_GROUPS_SUCCESS';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';
