export const FETCH_REGISTRATIONS_REQUEST = 'FETCH_REGISTRATIONS_REQUEST';
export const FETCH_REGISTRATIONS_SUCCESS = 'FETCH_REGISTRATIONS_SUCCESS';
export const FETCH_REGISTRATIONS_FAILED = 'FETCH_REGISTRATIONS_FAILED';

export const FETCH_REGISTRATION_REQUEST = 'FETCH_REGISTRATION_REQUEST';
export const FETCH_REGISTRATION_SUCCESS = 'FETCH_REGISTRATION_SUCCESS';
export const FETCH_REGISTRATION_FAILED = 'FETCH_REGISTRATION_FAILED';

export const ADD_REGISTRATION_REQUEST = 'ADD_REGISTRATION_REQUEST';
export const ADD_REGISTRATION_SUCCESS = 'ADD_REGISTRATION_SUCCESS';
export const ADD_REGISTRATION_FAILED = 'ADD_REGISTRATION_FAILED';

export const UPDATE_REGISTRATION_REQUEST = 'UPDATE_REGISTRATION_REQUEST';
export const UPDATE_REGISTRATION_SUCCESS = 'UPDATE_REGISTRATION_SUCCESS';
export const UPDATE_REGISTRATION_FAILED = 'UPDATE_REGISTRATION_FAILED';

export const DELETE_REGISTRATION_REQUEST = 'DELETE_REGISTRATION_REQUEST';
export const DELETE_REGISTRATION_SUCCESS = 'DELETE_REGISTRATION_SUCCESS';
export const DELETE_REGISTRATION_FAILED = 'DELETE_REGISTRATION_FAILED';

export const SET_REGISTRATIONS_PAGER = 'SET_REGISTRATIONS_PAGER';

export const HIDE_ALERT = 'HIDE_ALERT';
  