export const FETCH_DEPTS_SUCCESS = 'FETCH_DEPTS_SUCCESS';
export const FETCH_DEPTS_REQUEST = 'FETCH_DEPTS_REQUEST';
export const FETCH_DEPTS_FAILED = 'FETCH_DEPTS_FAILED';

export const FETCH_DEPT_SUCCESS = 'FETCH_DEPT_SUCCESS';
export const FETCH_DEPT_REQUEST = 'FETCH_DEPT_REQUEST';
export const FETCH_DEPT_FAILED = 'FETCH_DEPT_FAILED';

export const ADD_DEPTS_SUCCESS = 'ADD_DEPTS_SUCCESS';
export const ADD_DEPTS_REQUEST = 'ADD_DEPT_REQUEST';
export const ADD_DEPTS_FAILED = 'ADD_DEPT_FAILED';

export const UPDATE_DEPTS_SUCCESS = 'UPDATE_DEPTS_SUCCESS';
export const UPDATE_DEPTS_REQUEST = 'UPDATE_DEPT_REQUEST';
export const UPDATE_DEPTS_FAILED = 'UPDATE_DEPT_FAILED';

export const DELETE_DEPTS_SUCCESS = 'DELETE_DEPTS_SUCCESS';
export const DELETE_DEPTS_REQUEST = 'DELETE_DEPT_REQUEST';
export const DELETE_DEPTS_FAILED = 'DELETE_DEPT_FAILED';

export const SET_DEPTS_PAGER = 'SET_DEPTSS_PAGER';
export const HIDE_ALERT = 'HIDE_ALERT';
