export const FETCH_UNITS_REQUEST = 'FETCH_UNITS_REQUEST';
export const FETCH_UNITS_FAILED = 'FETCH_UNITS_FAILED';
export const FETCH_UNIT_SUCCESS = 'FETCH_UNIT_SUCCESS';
export const FETCH_UNITS_SUCCESS = 'FETCH_UNITS_SUCCESS';