export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_FAILED = 'FETCH_ITEMS_FAILED';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEM_SUCCESS';
export const SET_ITEMS_PAGER = 'SET_ITEMS_PAGER';

export const FETCH_ITEM_REQUEST = 'FETCH_ITEM_REQUEST';
export const FETCH_ITEM_FAILED = 'FETCH_ITEM_FAILED';
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';

export const ADD_ITEMS_REQUEST = 'ADD_ITEMS_REQUEST';
export const ADD_ITEMS_FAILED = 'ADD_ITEMS_FAILED';
export const ADD_ITEMS_SUCCESS = 'ADD_ITEMS_SUCCESS';

export const UPDATE_ITEMS_REQUEST = 'UPDATE_ITEMS_REQUEST';
export const UPDATE_ITEMS_FAILED = 'UPDATE_ITEMS_FAILED';
export const UPDATE_ITEMS_SUCCESS = 'UPDATE_ITEMS_SUCCESS';

export const DELETE_ITEMS_REQUEST = 'DELETE_ITEMS_REQUEST';
export const DELETE_ITEMS_FAILED = 'DELETE_ITEMS_FAILED';
export const DELETE_ITEMS_SUCCESS = 'DELETE_ITEMS_SUCCESS';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';
