export const FETCH_ICD10S_REQUEST = 'FETCH_ICD10S_REQUEST';
export const FETCH_ICD10S_SUCCESS = 'FETCH_ICD10S_SUCCESS';
export const FETCH_ICD10S_FAILED = 'FETCH_ICD10S_FAILED';
export const SET_ICD10S_PAGER = 'SET_ICD10S_PAGER';
  