export const FETCH_VISITIONS_REQUEST = 'FETCH_VISITIONS_REQUEST';
export const FETCH_VISITIONS_SUCCESS = 'FETCH_VISITIONS_SUCCESS';
export const FETCH_VISITIONS_FAILED = 'FETCH_VISITIONS_FAILED';

export const FETCH_VISITION_REQUEST = 'FETCH_VISITION_REQUEST';
export const FETCH_VISITION_SUCCESS = 'FETCH_VISITION_SUCCESS';
export const FETCH_VISITION_FAILED = 'FETCH_VISITION_FAILED';

export const ADD_VISITION_REQUEST = 'ADD_VISITION_REQUEST';
export const ADD_VISITION_SUCCESS = 'ADD_VISITION_SUCCESS';
export const ADD_VISITION_FAILED = 'ADD_VISITION_FAILED';

export const UPDATE_VISITION_REQUEST = 'UPDATE_VISITION_REQUEST';
export const UPDATE_VISITION_SUCCESS = 'UPDATE_VISITION_SUCCESS';
export const UPDATE_VISITION_FAILED = 'UPDATE_VISITION_FAILED';

export const DELETE_VISITION_REQUEST = 'DELETE_VISITION_REQUEST';
export const DELETE_VISITION_SUCCESS = 'DELETE_VISITION_SUCCESS';
export const DELETE_VISITION_FAILED = 'DELETE_VISITION_FAILED';

export const SET_VISITIONS_PAGER = 'SET_VISITIONS_PAGER';

export const HIDE_ALERT = 'HIDE_ALERT';
  