export const FETCH_BARTHELS_REQUEST = 'FETCH_BARTHELS_REQUEST';
export const FETCH_BARTHELS_SUCCESS = 'FETCH_BARTHELS_SUCCESS';
export const FETCH_BARTHELS_FAILED = 'FETCH_BARTHELS_FAILED';

export const ADD_BARTHELS_REQUEST = 'ADD_BARTHELS_REQUEST';
export const ADD_BARTHELS_SUCCESS = 'ADD_BARTHELS_SUCCESS';
export const ADD_BARTHELS_FAILED = 'ADD_BARTHELS_FAILED';

export const SET_BARTHELS_PAGER = 'SET_BARTHELS_PAGER';
  