export const FETCH_ITEM_TYPE_REQUEST = 'FETCH_ITEM_TYPE_REQUEST';
export const FETCH_ITEM_TYPE_SUCCESS = 'FETCH_ITEM_TYPE_SUCCESS';
export const FETCH_ITEM_TYPE_FAILED = 'FETCH_ITEM_TYPE_FAILED';
export const FETCH_ITEM_TYPES_REQUEST = 'FETCH_ITEM_TYPES_REQUEST';
export const FETCH_ITEM_TYPES_SUCCESS = 'FETCH_ITEM_TYPES_SUCCESS';
export const FETCH_ITEM_TYPES_FAILED = 'FETCH_ITEM_TYPE_FAILED';