export const FETCH_PERSONS_SUCCESS = 'FETCH_PERSONS_SUCCESS';
export const FETCH_PERSONS_REQUEST = 'FETCH_PERSONS_REQUEST';
export const FETCH_PERSONS_FAILED = 'FETCH_PERSONS_FAILED';

export const FETCH_PERSON_SUCCESS = 'FETCH_PERSON_SUCCESS';
export const FETCH_PERSON_REQUEST = 'FETCH_PERSON_REQUEST';
export const FETCH_PERSON_FAILED = 'FETCH_PERSON_FAILED';

export const ADD_PERSONS_SUCCESS = 'ADD_PERSONS_SUCCESS';
export const ADD_PERSONS_REQUEST = 'ADD_PERSONS_REQUEST';
export const ADD_PERSONS_FAILED = 'ADD_PERSONS_FAILED';

export const UPDATE_PERSONS_SUCCESS = 'UPDATE_PERSONS_SUCCESS';
export const UPDATE_PERSONS_REQUEST = 'UPDATE_PERSONS_REQUEST';
export const UPDATE_PERSONS_FAILED = 'UPDATE_PERSONS_FAILED';

export const DELETE_PERSONS_SUCCESS = 'DELETE_PERSONS_SUCCESS';
export const DELETE_PERSONS_REQUEST = 'DELETE_PERSONS_REQUEST';
export const DELETE_PERSONS_FAILED = 'DELETE_PERSONS_FAILED';

export const SET_PERSONS_PAGER = 'SET_PERSONS_PAGER';
export const HIDE_ALERT = 'HIDE_ALERT';
