export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const ADD_ORDERS_SUCCESS = 'ADD_ORDERS_SUCCESS';
export const UPDATE_ORDERS_SUCCESS = 'UPDATE_ORDERS_SUCCESS';
export const DELETE_ORDERS_SUCCESS = 'DELETE_ORDERS_SUCCESS';

export const SET_ORDERS_PAGER = 'SET_ORDERS_PAGER';
