export const FETCH_HOSPS_REQUEST = 'FETCH_HOSPS_REQUEST';
export const FETCH_HOSPS_SUCCESS = 'FETCH_HOSPS_SUCCESS';
export const FETCH_HOSPS_FAILED = 'FETCH_HOSPS_FAILED';
export const SET_HOSPS_PAGER = 'SET_HOSPS_PAGER';
export const FETCH_PCUS_REQUEST = 'FETCH_PCUS_REQUEST';
export const FETCH_PCUS_SUCCESS = 'FETCH_PCUS_SUCCESS';
export const FETCH_PCUS_FAILED = 'FETCH_PCUS_FAILED';
export const SET_PCUS_PAGER = 'SET_PCUS_PAGER';
  